config/routes.rb
Rails.application.routes.draw do

  get 'messages/new'
  devise_for :users
  resources :users, only: :show

  root 'hobbies#index'

  resources :hobbies do
    # コメント機能
    resources :messages, only: [:create, :destroy]
    # カテゴリー機能
    mount ActionCable.server, at: '/cable'
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hobbies
  has_ancestry

  def self.category_parent_array_create
    category_parent_array = ['---']
    Category.where(ancestry: nil).each do |parent|
      category_parent_array << [parent.name, parent.id]
    end
    category_parent_array
  end

  def self.maltilevel_category_create(_category_id, parent_id, children_id, grandchildren_id)
    category = Category.find(parent_id) if parent_id.present? && parent_id != '--'

    category = Category.find(children_id) if children_id.present? && children_id != '--'

    category = Category.find(grandchildren_id) if grandchildren_id.present? && grandchildren_id != '--'
  end
  
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  # バリデーション

  # タイトル、あらすじ、おすすめポイント
  with_options presence: true do
    validates :title, :synopsis, :recommended, :user_id
  end

  # 公開年月日
  with_options presence: { message: 'が未選択です。' } do
    validates :release_date
  end

  # アソシエーション
  belongs_to :category
  belongs_to :user
  has_many :messages

  def self.search(search)
    if search != ""
      Hobby.where('title LIKE(?)', "%#{search}%")
    else
      Hobby.all
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  # バリデーション
  validates :text, presence: true

  # アソシエーション
  belongs_to :user
  belongs_to :hobby
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ニックネーム
  validates :nickname, presence: true

  # パスワード
  with_options confirmation: { message: '確認用パスワードとパスワードは一致しないといけません。' },
               format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/, message: 'は半角英数字混合での入力が必須です。' } do
    validates :password
    validates :password_confirmation, presence: true
  end

  # プロフィール
  validates :profile, presence: true

  # バリデーション
  has_many :hobbies
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :nickname, :profile])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :encrypted_password])
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_category, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_hobby, only: [:show, :edit, :update, :destroy, :search]
  before_action :session_user, only: [:edit, :update, :destroy]
  #before_action :move_to_index, except: [:index, :show, :search]

  def index
    # 情報の取得
    @hobbies = Hobby.includes(:user).order('created_at DESC')
  end

  def search
    #@hobbies = Hobby.search(params[:keyword])
  end

  def new
    @hobby = Hobby.new
    @category_parent_array = ['---']
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def create
    @hobby = Hobby.new(hobby_params)
    @hobby.user_id == current_user.id
    if @hobby.valid?
      @hobby.save
      Category.maltilevel_category_create(
        @hobby,
        params[:parent_id],
        params[:children_id],
        params[:grandchildren_id]
      )
      redirect_to root_path
      flash[:notice] = '投稿が完了しました。'
    else
      @category_parent_array = ['---']
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      render :new
    end
  end

  def get_category_children
    @category_children = Category.find_by(name: params[:parent_name].to_s, ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id].to_s).children
  end

  def show
    @category_grandchild = @hobby.category
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    # メッセージモデルの記述
    @message = Message.new
    @messages = @hobby.messages.order('created_at DESC')
  end

  def edit
    @category_grandchild = @hobby.category
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    # カテゴリー一覧を作成
    @category = Category.find(params[:id])
    # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
    @category_children = @hobby.category.parent.parent.children
    # 紐づく孫カテゴリーの一覧を配列で取得
    @category_grandchildren = @hobby.category.parent.children
  end

  def update
    # 編集画面で選択された新しいカテゴリー
    @category_grandchild = Category.find(hobby_params[:category_id])
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    if @hobby.update(hobby_params)
      category = Category.where(hoby_id: @hobby.id)
      category.destroy_all
      Category.maltilevel_category_create(
        @hobby,
        params[:parent_id],
        params[:children_id],
        params[:grandchildren_id]
      )
      redirect_to @hobby
      flash[:notice] = '投稿の編集が完了しました。'
    else
      @category_parent_array = Category.category_parent_array_create
      render :edit
    end
  end

  def destroy
    if @hobby.destroy
      redirect_to root_path
      flash[:notice] = '投稿を削除しました。'
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = '投稿の削除に失敗しました。'
    end
  end

  private

  def hobby_params
    params.require(:hobby).permit(:title, :release_date, :recommended, :synopsis, :category_id).merge(user_id: current_user.id)
  end

  def set_hobby
    @hobby = Hobby.find(params[:id])
  end

  def set_category
    @category_parent_array = Category.where(ancestry: nil)
  end

  def session_user
    redirect_to root_path if current_user.id != @hobby.user_id
  end

  #def move_to_index
    #unless user_signed_in?
      #redirect_to action: :index
    #end
  #end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = Message.new(message_params)
    @hobby = Hobby.find(params[:hobby_id])
    @messages = @hobby.messages.includes(:user).order('created_at DESC')
    if @message.valid?
      @message.save
      ActionCable.server.broadcast 'message_channel', message: @message, nickname: @message.user.nickname,
                                                      time: @message.created_at.strftime("%Y/%m/%d %H:%M:%S"), id: @hobby.id
      # redirect_to hobby_path(@hobby.id)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.json { render json: @message.id}
    end
  end

  private

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, hobby_id: params[:hobby_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @hobbies = @user.hobbies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobby_helper.rb
module HobbyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/_form.html.haml
= form_with model: @hobby, local: true do |f|
  .field
    %span.indispensable 必須
    = f.label :title, "作品名"
    %br/
    = f.text_field :title, id:"hobby_title"
  .field
    %span.indispensable 必須
    = f.label :synopsis, "大まかなあらすじ"
    %br/
    = f.text_area :synopsis, class: :form__text, id:"hobby_catch_copy"
  .field
    %span.indispensable 必須
    = f.label :recommended, "おすすめポイント"
    %br/
    = f.text_area :recommended, class: :form__text, id:"hobby_concept"
  .field
    %span.indispensable 必須
    = f.label :release_date, "公開・発売年月日"
    %br/
    = raw sprintf(                               |
      f.date_select(                             |
        :release_date,                           |
        class:'select-release',                  |
        id:"release-date",                       |
        use_month_numbers: true,                 |
        prompt:'--',                             |
        start_year: 1930,                        |
        end_year: (Time.now.year - 1),           |
        date_separator: '%s'),                   |
      "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" |
  .field
    %span.indispensable 必須
    =f.label "カテゴリ"
    %br/
    .form-title__required
      %label
  .form-input-select
    = f.select :category_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
  .pulldown.hobby_input__body__category__children#children_box
  .pulldown.hobby_input__body__category__grandchildren#grandchildren_box
  %br/
  .actions
    = f.submit "保存する", class: :form__btn

app/views/hobbies/edit.html.haml
.main
  .inner
    .form__wrapper
      %h2.page-heading おすすめ作品の編集
      = form_with model: @hobby, local: true do |f|
        .field
          %span.indispensable 必須
          = f.label :title, "作品名"
          %br/
          = f.text_field :title, id:"hobby_title"
        .field
          %span.indispensable 必須
          = f.label :synopsis, "大まかなあらすじ"
          %br/
          = f.text_area :synopsis, class: :form__text, id:"hobby_catch_copy"
        .field
          %span.indispensable 必須
          = f.label :recommended, "おすすめポイント"
          %br/
          = f.text_area :recommended, class: :form__text, id:"hobby_concept"
        .field
          %span.indispensable 必須
          = f.label :release_date, "公開・発売年月日"
          %br/
          = raw sprintf(                               |
            f.date_select(                             |
              :release_date,                           |
              class:'select-release',                  |
              id:"release-date",                       |
              use_month_numbers: true,                 |
              prompt:'--',                             |
              start_year: 1930,                        |
              end_year: (Time.now.year - 1),           |
              date_separator: '%s'),                   |
            "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" |
        .field
          %span.indispensable 必須
          =f.label "カテゴリ"
          %br/
          .form-title__required
            %label
        .form-input-select
          = f.collection_select :category_id, @category_parent_array, :id, :category, { selected: @category_parent },{ class:"select" }
          = f.collection_select :category_id, @category_children, :id, :category,{ selected: @category_child}, {class:"select", id: "child_category"}
          = f.collection_select :category_id, @category_grandchildren, :id, :category,{ selected: @category_grandchild},{class:"select", id: "grandchild_category"}
                
        %br/
        .actions
          = f.submit "保存する", class: :form__btn

app/views/hobbies/index.html.haml
%main.main
  .inner
    .greeting2{ style:'text_align: left;' }
      = "▼ Everyone's  favorite"
    .card__wrapper
      .card__tops
        - @hobbies.each do |hobby|
          .card__top
            = link_to hobby.title, hobby_path(hobby.id), method: :get, class: :card__title
            .card__body
              = hobby.recommended
              %p.card__summary
              = link_to hobby.user.nickname, user_path(hobby.user.id) , class: :card__user

app/views/hobbies/new.html.haml
.main
  .inner
    .form__wrapper
      %h2.page-heading 新規お気に入り作品投稿
      = render 'layouts/error_message', model: @hobby
      = render partial: "form"

app/views/hobbies/search.html.haml
= form_with(url: search_hobbies_path, local: true, method: :get, class: 'search-form') do |f|
  = f.text_field :keyword, placeholder: '投稿を検索する', class: 'search-input'
  = f.submit '検索', class: 'search-btn'
.contents-row
  @hobbies.each do |hobby|
    .card__top
      = link_to hobby.title, hobby_path(hobby.ids), method: :get, class: :card__title
    .card__body
      = hobby.recommended
      %p.card__summary
      = link_to hobby.user.nickname, user_path(hobby.user.id) , class: :card__user

app/views/hobbies/show.html.haml
%main.main
  .inner
    .greeting2
      = '▼ おすすめ作品名'
      .greeting3
        - if user_signed_in? && current_user.id == @hobby.user_id
          .hobby__manage
            = link_to "編集する", '#', class: :hobby__btn
            = link_to "削除する", hobby_path(@hobby), method: :delete, class: :hobby__btn
    .detail-title
      = @hobby.title
    %br.type__wrapper
      %table.detail-table
        %tr
          %th.detail-hobby 投稿者
          %td.detail-value 
            = link_to "#{@hobby.user.nickname}", user_path(@hobby.user.id)
        %tr
          %th.detail-hobby 大まかなあらすじ
          %td.detail-value
            = @hobby.synopsis
        %tr
          %th.detail-hobby おすすめポイント
          %td.detail-value
            = @hobby.recommended
        %tr
          %th.detail-hobby 公開年月日
          %td.detail-value
            = @hobby.release_date
        %tr
          %th.detail-hobby カテゴリー
          %td.detail-value
            - if [1, 23, 44, 64].include?(@category_id)
              = link_to "#{@category_grandchild.category}","#"
            - else
              - if @category_parent == nil
                = link_to @category_child.name,"#"
                = '/'
                = link_to @category_grandchild.name,"#"
              - else
                = link_to @category_parent.name,"#"
                = '/'
                = link_to @category_child.name,"#"
                = '/'
                = link_to @category_grandchild.name,"#"
  .inner2
    .comment-box
      .greeting2
        = '▼ コメント一覧'
        - if @messages
          #comments
          - @messages.each do |message|
            .comments_lists{data: {message_id: "#{message.id}"}}
              .comment_top{ style: 'color:gray;' 'font-size: 15px;' 'display: flex;' 'justify-content: space-between;' }
                %div
                  = message.user.nickname
                %div
                  = l message.created_at
              .comments_bottom{ style: 'color:black;' 'display: flex;' 'justify-content: flex-start;' }
                %p
                  = message.text
              .comment_bottom_delete
                -if user_signed_in? && current_user == message.user.id
                  %button.comment__delete__button
                    = link_to hobby_message_path(message.hobby.id, message.id), method: :delete do
                      = icon('fa', 'trash')
      .comment__form
        %script{ type: 'javascript/channels', src: 'message_channel.js'}
        - if signed_in?
          = form_with model: [@hobby, @message], local: true do |f|
            = f.text_area :text, class: 'comment-text', id: 'comment_text'
            %p.comment-warn
              = '相手のことを考え、丁寧なコメントを心がけましょう。'
              %br= '不快な言葉遣いなどは、利用制限や退会処分となります。'
            %button.comment_btn{ name: "button", type: "submit" }
              = 'コメントする'

app/views/layouts/_error_message.html.haml
- if model.errors.any?
  .alert
    %ul
      -model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title LikeShere
    = csrf_meta_tags
    = csp_meta_tag
    %script { src: 'http://ajax.googleapis.com/ajax/libs/jquery-3.4.1.min.js' }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap", :rel => "stylesheet"}/
  %body
    %header.header
      .inner
        .nav
          .nav__left
            = link_to "LikeShere", root_path, class: :apptitle
            .sub-title{ style: "color:#66cccc" }
              = '~スキを探そう  シェアしよう~'
          - if user_signed_in?
            .nav__right
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout
              = link_to "New Like", new_hobby_path, class: :nav__btn
              .greeting
                = "こんにちは ! "
                = link_to current_user.nickname, edit_user_password_path(current_user), |
                  class: :greeting__link                                                |
                = "さん"
          - else
            .nav__right
              = link_to "ログイン", user_session_path, class: :nav__btn
              = link_to "新規登録", new_user_registration_path, class: :nav__btn
    = yield
    %footer.footer
      %p.copyright Copyright © Like Shere All rights reserved.

app/views/users/show.html.haml
.main
  .inner
    %br.type__wrapper
      .page-heading
        = @user.nickname
        = 'さんの情報'
      %table.detail-table
        %tr
          %th.detail-hobby ユーザー名
          %td.detail-value
            = @user.nickname
        %tr
          %th.detail-hobby プロフィール
          %td.detail-value
            = @user.profile
      .page-heading
        = @user.nickname
        = 'さんのおすすめ作品一覧'
        .user__card
        - @hobbies.each do |hobby|
          .card__top
            = link_to hobby.title, hobby_path(@hobbies.ids), method: :get, class: :card__title
            .card__body
              %p.card__summary
                = hobby.recommended
                = link_to hobby.user.nickname, user_path(hobby.user.id) , class: :card__user